### PR TITLE
Add https://steamcommunity.com/sharedfiles/filedetails/?id=2018524991

### PR DESCRIPTION
**Pull request by wrefgtzweve**

### CODE REVIEW

**Comment by wrefgtzweve** [comment]
fully clientside btw, i checked it

**Review by plally — APPROVED** [review]

**Comment by sarahsturgeon** [comment]
Not a fan of the big ad in the top left of the overlay :/

I'm not just saying this to be an ass, but what if we forked it? Seems like we could add a ton more features in there, and remove the stupid branding.

**Comment by wrefgtzweve** [comment]
i don't think forking would be needed here, literally have starfalls that do it better. i could deffo just make a addon for it if needed

**Comment by sarahsturgeon** [comment]
I would personally enjoy this as an addon with CFC standards

**Comment by wrefgtzweve** [comment]
i'll place it on my todo list, will be uploading it to the workshop though, still wanna do that sometime

**Pull request closed without merging**
